enum PokemonActionTypes {
  SET_POKEMON           = 'SET_POKEMON',
  SEARCH_POKEMONS       = 'SEARCH_POKEMONS',
  GET_POKEMONS_START    = 'GET_POKEMONS_START',
  GET_POKEMONS_SUCCESS  = 'GET_POKEMONS_SUCCESS',
  GET_POKEMONS_FAILURE  = 'GET_POKEMONS_FAILURE'
}

export default PokemonActionTypes;
